### ISSUE TITLE
Script for Hikvision cameras with SD card - download .jpeg timed captures?

### ISSUE THREAD

**Issue by mrmaximas** [Tedyst/HikLoad#12]
it's possible?

**Comment by Tedyst** [comment]
If I understand correctly, `.jpeg timed captures` means to get some frames from each stream and store them as .jpeg?

**Comment by mrmaximas** [comment]
no. hikvision cameras can make pictures, by event or timed captures. 
this pictures are stored on sd or nvr/dvr/external hdd

**Comment by mrmaximas** [comment]
like this for example 
https://github.com/cfryanr/hikvision-download-assistant

**Comment by Tedyst** [comment]
I tried reimplementing that repo, and I added a `--photos` flag, but I don't think it would work. If it dosen't, could you please send the line from the script startup that starts with `[root -                 main() ] ChannelList: `. It should contain the list of all channels, maybe I could use it to trace how exactly are the photos implemented. (The ISAPI document that I have does not specify in any way that a channel ending in 3 exists)

**Comment by mrmaximas** [comment]
[root -                 main() ] Found channels []

**Comment by Tedyst** [comment]
And the channelList when using --debug ?

**Comment by mrmaximas** [comment]
for example i found this url using hikvision-download-assistant
, {
    "mediaType" : "PHOTO",
    "startTime" : 1632470656000,
    "endTime" : 1632470656000,
    "eventType" : "TIMING",
    "curlCommand" : "curl -f --anyauth --user admin:pass 'http://11.11.11.11/ISAPI/Streaming/tracks/103/?starttime=20210924T080416Z&endtime=20210924T080416Z&name=ch01_00000000013022600&size=983775' --output 2021-09-24T11-04-16.jpeg"
  } ]

**Comment by Tedyst** [comment]
I looked at that repo, and it only looks for the 103 channel, without it being advertised by the camera. For now, I forced looking at that stream for every channel, maybe it will work.

**Comment by mrmaximas** [comment]
> I looked at that repo, and it only looks for the 103 channel, without it being advertised by the camera. For now, I forced looking at that stream for every channel, maybe it will work.

it's works!

**Comment by Tedyst** [comment]
I guess we can close the issue now, since you said that it works. If there are any more problems, be sure to create another issue or reply to this one.
