### ISSUE TITLE
Error when downloading single file

### ISSUE THREAD

**Issue by MinseokKang003** [Tedyst/HikLoad#15]
Hi, Thanks for the awesome package.

I found an error when trying to download a single recording.

I think the error occurs because the received recording data format is different when there are multiple recordings, and only one recording.

When there is only one recording, I needed to fix the existing code to this and remove the for loop.
`recording = recordings['CMSearchResult']['matchList']['searchMatchItem']`

I hope this issue could be fixed.

I'm sorry I couldn't help much, I'm a noob in Python.

**Comment by Tedyst** [comment]
I pushed to master a fix to this issue. Can you please verify that it works as intented? Thanks.

**Comment by MinseokKang003** [comment]
Works as intended. Thanks!
