### ISSUE TITLE
Concatenating videos from one camera

### ISSUE THREAD

**Issue by MiraPurkrabek** [Tedyst/HikLoad#24]
First of all, thank you for the Python Hikvision API. It's a great job.

The API downloads videos from the NVR as they are stored - in 1 GB chunks. Most users (I suppose) would like one video per camera of the required length. Did you consider adding the concatenating feature (option) to the app?

I imagine the download queue would contain information about the camera (which is discarded while creating the queue). Once all recordings of one camera are downloaded, we would concat the videos using FFmpeg. It should be enough to copy the encoding since all videos are in the same format and encoding, so the concatenation would not take so long. 
Further (which I suppose could be another pull request and/or issue), we could cut the resulting video to contain only the required time from arguments.

I already do the same in my post-processing script, and the concatenation usually runs between 60 - 150 times faster than the duration of the video.

The proposed solution would only slow the process marginally (without re-encoding, always saving new videos and deleting old ones). It could blow up in terms of memory when downloading longer videos. Still, we can always check for the video length before running this process or prompt the user for confirmation.

Since I need the functionality, I will implement it in my fork. Please let me know if you'd be interested, and I can implement it for the HikLoad.

**Comment by Tedyst** [comment]
Hi! Storing the recordings in one video per camera sounds like a great idea! I suggest this functionality be kept behind a command-line flag, like `--concatenate` (it's up to you). When you finish implementing the feature, I would be eager to see it and merge it.
