### ISSUE TITLE
module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by imdokyun** [Tedyst/HikLoad#27]
hikload doesn't run in python==3.8?

**Comment by Tedyst** [comment]
This should have been fixed in b3dc052458293490c615ac1d5da5e25974ed3279. Can you please verify that it now works?

**Comment by Tedyst** [comment]
Feel free to reopen the issue if it is still applicable.

**Comment by imdokyun** [comment]
Thanks, sir 
It now works good!!!
