### ISSUE TITLE
Unauthorized user

### ISSUE THREAD

**Issue by fnando1995** [Tedyst/HikLoad#3]
Hello,

I'm trying to use this code as base for an automatic video download from a hikvision NVR.

I have the problem that even though I use the correct user, pass and camera, I always get an unauthorized user response.

```
>>> responseXML = requests.post(serverpath, data, headers).text
>>> responseXML
<?xml version="1.0" encoding="UTF-8" ?>
<userCheck>
<statusValue>401</statusValue>
<statusString>Unauthorized</statusString>
</userCheck>
```

In the DVR the camara names are "Camara 01" "Camera 02" .... but I use as indicated in the config life "101" "201"

Any help will be appreciated.

thanks
E.M.

**Comment by Tedyst** [comment]
Hi. Do you have by any chance any non-alphabet characters in your password/username that might trigger this bug?
If yes, can you try to escape them with \\ and see if this works ?

**Comment by fnando1995** [comment]
Hello @Tedyst 
Actually no, lets say this are my credentials
user: emmanuel
pass: Emmanuel.

**Comment by Tedyst** [comment]
I have tried setting the password to my DVR to `Emmanuel.`, but I couldn't reproduce the bug. But I still moved from using my basic http auth to the proper one from the requests package. Can you verify if this is fixed in master? 
If not, can you see if `http://user:password@NVRAddress/ISAPI/System/capabilities` works in the browser?

**Comment by fnando1995** [comment]
@Tedyst Sorry! it is not "Emmanuel." is just "Emmanuel" XD, that dot failed there hahaha.

I tried the url you mentioned and it works. Any clues?

thanks for your help by the way

**Comment by Tedyst** [comment]
You said that you were using this code as base for something. Did you include the username and password in the serverpath or in the auth parameter like here? https://github.com/Tedyst/HikLoad/blob/b3eb7be65bd34040992e1b7b15f23ff4ce2e8dc4/main.py#L32-L33

**Comment by fnando1995** [comment]
Ok look, i have this:

I have too DVRs, One with IP cameras and other with no IP cameras.

DVR without IP cameras: Still got the unauthorized problem
```
Trying to download from camera 101
<?xml version="1.0" encoding="UTF-8" ?>
<userCheck>
<statusValue>401</statusValue>
<statusString>Unauthorized</statusString>
</userCheck>
```
In the DVR the names are "Camera 01", "Camera 02" and so on, maybe thats something to check?

DVR with IP cameras
It give me a response but the .mp4 file is a 0 bytes file... 

```
Trying to download from camera 101
<?xml version="1.0" encoding="UTF-8" ?>
<CMSearchResult version="1.0" xmlns="urn:ISAPIlliance-org">
<searchID>{c85ab0c7-f380-0001-e33b-a030eeb671f0}</searchID>
<responseStatus>true</responseStatus>
<responseStatusStrg>OK</responseStatusStrg>
<numOfMatches>1</numOfMatches>
<matchList>
<searchMatchItem>
<sourceID>{00000000-0000-0000-0000-000000000000}</sourceID>
<trackID>101</trackID>
<timeSpan>
<startTime>2020-01-23T10:00:00Z</startTime>
<endTime>2020-01-23T10:10:00Z</endTime>
</timeSpan>
<mediaSegmentDescriptor>
<contentType>video</contentType>
<codecType>H.264-BP</codecType>
<playbackURI>rtsp://xxx.xxx.xxx.xxx/Streaming/tracks/101/?starttime=20200123T100000Z&amp;endtime=20200123T101000Z&amp;name=02000003397000000&amp;size=1064366528</playbackURI>
</mediaSegmentDescriptor>
<metadataMatches>
<metadataDescriptor>recordType.meta.hikvision.com/timing</metadataDescriptor>
</metadataMatches>
</searchMatchItem>
</matchList>
</CMSearchResult>
```


This is actually pretty unusul i suppose. Especially knowing that i also test datetime.now()-timedelta(days=1) to ensure at leat all the video is save. check also time is 10:00AM-10:10AM in both (today and todays-1).

thanks!

**Comment by BilalS10** [comment]
Dear friends,

I am struggling to download video from my hikvision camera ( model no  : DS-2CD5A26G0-IZS ).
I have kept the camera on continuous recording mode and the video is being stored in the sd card.
Have tried multiple libraries from git but no success.
Was trying your library. I ran the main.py after changing the config file but got the same error ( unauthorized request). Please help me with the same.
My objective is to download the video by giving it start time and end time.

**Comment by Tedyst** [comment]
Can somebody verify if digest is the default authentication method for the NVR? This problem may occur because the auth method must be set to digest/basic, because this library does not yet support digest authentication. I will try to add it in the future.

**Comment by fnando1995** [comment]
I use [YOHO_LAB](https://github.com/YOHO-LAB/save-hikvision-record) code, maybe will help you

**Comment by BilalS10** [comment]
Sure..
Already trying with that..
Thank you :)

**Comment by BilalS10** [comment]
> Can somebody verify if digest is the default authentication method for the NVR? This problem may occur because the auth method must be set to digest/basic (because this library does not yet support digest authentication). I will try to add it in the future.

Yep it is the default as it shows the same in the configuration parameters..
Will try after changing it to digest/basic.
