### ISSUE TITLE
Download video skipping frames

### ISSUE THREAD

**Issue by fnando1995** [Tedyst/HikLoad#5]
Hello @Tedyst 

Is there a way to use the Hikvision SDK to download video, but skipping frames?. I want to reduce bandwich comsumption skipping some frame from the DVR/NVR directly. Lets put an example:

If I download a video from 2021-04-13 15:20:00 to 2021-04-13 15:25:00 I will have a 5 minutes video. Let's say the device save the video with a fps od 10. This means this downloaded video have 3000 frames. Now I want to skipp 9 frames per each frame downloaded, so for this example I will only download 300 frames. The downloaded frames will be: frame1, frame11, frame21, frame 31, and so on. (note that 9 frames were skipped between each downloaded frame).

Is there a way to do this?

Thanks in advance for any help.

**Comment by Tedyst** [comment]
Hello. I have introduced the ability to enable skipping frames in the commit ddaa243e561aef3170e421b6aa0a635b11a3ebc1. Can you see if this is the requested feature? I will close this issue after you confirm this is what you wanted.

**Comment by fnando1995** [comment]
Hello @Tedyst 

I check that you first download and then skip the video using ffmpeg. I want to download it already skipped.

Thanks.

**Comment by Tedyst** [comment]
I have added a way to skip the first x seconds of a stream by specifying the option `skipSeconds` or by using the config (for the main example file)

**Comment by fnando1995** [comment]
I do not want to skip the first N seconds. I want to skip N seconds for every frame downloaded. Or in other words, skip FPS*N frames for every downloaded frame.

Example:
Lets say I want a video. This video have 10 frames per second, and I want to skip 3 frames per downloaded frame. The process will be:

for second 1 video have frames: f1,f2,f3,f4,f5,f6,f7,f8,f9,f10. but I want to download frames: f1,f5,f9
for second 2 video have frames: f11,f12,f13,f14,f15,f16,f17,f18,f19,f20. but I want to download frames: f13,f17
for second 3 video have frames: f21,f22,f23,f24,f25,f26,f27,f28,f29,f30. but I want to download frames: f21,f25,f29

... and so on. Note that I skipped 3 frames between each downloaded frame. Is this posible to be done from the DVR/NVR directly?, I do not want to download the video and then skip, I want to download the skipped video directly from the net device. Frames 1,5,9,13,17,21,25,29 should be the only frames downloaded from the net device.
