### ISSUE TITLE
Download recorded files Error

### ISSUE THREAD

**Issue by rhdgkr001** [Tedyst/HikLoad#7]
After modifying config.py, I ran main.py, but the following error occurred.
Would you give me a hand?

ERROR:root:Got the response: OrderedDict([('userCheck', OrderedDict([('statusValue', '401'), ('statusString', 'Unauthorized')]))])

**Comment by Tedyst** [comment]
Does the password/username include by any chance the character `\`? The Python interpreter is sometimes weird with these types of strings.

**Comment by rhdgkr001** [comment]
No, \characters are not included. Is it an error caused by a mismatch in the password?
I.D : admin
P.W : 1234

(I checked that the account is logged in through the i-vms program)

**Comment by Tedyst** [comment]
That's what I think it could be. But I am not sure at the moment.

**Comment by rhdgkr001** [comment]
Oh, I don't use docker, is it because of that?

**Comment by Tedyst** [comment]
Shouldn't really be a problem, but you could try. In a few hours I will have time to check the code where this issue occurs specifically.

**Comment by Tedyst** [comment]
By looking at the ISAPI pdf, I found that a 401 response means that the Authorization headers are not being sent in the request. I am not sure what causes this, but I am still looking into it.

**Comment by rhdgkr001** [comment]
I had to create a new user on the camera using an operator role and selecting the roles.
Response was then converted to [200]!
I still don't know why I can't access my 'admin' account, but I succeeded in moving on to the next line.
Thank you for helping me.
