### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by rhdgkr001** [Tedyst/HikLoad#8]
I would like to inquire because the following error occurred when executing the 'getList(response)' function of main().

Traceback (most recent call last):
  File "./main.py", line 49, in <module>
    main()
  File "./main.py", line 40, in main
    for stream in getList(response):
  File "./hikload/util.py", line 114, in getList
    url = i["ns0:mediaSegmentDescriptor"]["ns0:playbackURI"].replace("rtsp://", "rtsp://" + getConfig('user') + ":" + getConfig("password") + "@", 1)

TypeError: string indices must be integers

※ In the 112th line of util.py, insert print(i) as follows, and the result is 'ns0:sourceID'.

**Comment by Tedyst** [comment]
Hey! I actually tried rewriting the whole project today to completely fix this issue and make it more maintainable. Can you check if the code that can be found in #9 does have this problem?
